amicontained-job:      
  image: alpine:latest
  stage: test
  
  before_script:
    - apk --no-cache add curl
  
  script:
    - echo "Testing amicontained..."
    - export AMICONTAINED_SHA256="d8c49e2cf44ee9668219acd092ed961fc1aa420a6e036e0822d7a31033776c9f"
    - curl -fSL "https://github.com/genuinetools/amicontained/releases/download/v0.4.9/amicontained-linux-amd64" -o "/usr/local/bin/amicontained" && echo "${AMICONTAINED_SHA256}  /usr/local/bin/amicontained" | sha256sum -c - && chmod a+x "/usr/local/bin/amicontained"
    - amicontained > amicontained.txt
  artifacts:
    paths:
      - amicontained.txt
