docker-job:      
  image: python:latest
  stage: test

  before_script:
  - curl -fSL "https://github.com/brompwnie/botb/releases/download/1.8.0/botb-linux-amd64" -o "botb-linux-amd64" && chmod +x botb-linux-amd64

  script:
    - echo "Testing docker-socket"
    - python3 tools/docker/test.py > docker_test.txt
  artifacts:
    paths:
      - docker_test.txt
